version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    environment:
      - NODE_ENV=development
      - MONGO_USER=root
      - MONGO_PASSWORD=example
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
