version: '3'
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - type: volume  # The type of volume (e.g., 'bind' or 'volume')
        source: mongo-db  # The name of the volume
        target: /data/db  # The target path inside the container

volumes:
  mongo-db: