version: '3'
services:
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: development
    environment:
      - NODE_ENV=devlopment
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev